<?php
    if(isset($_POST['send_reset_password']))
    {
        $email=$_POST['email'];
        $otp = rand(100000,999999);
        $query="SELECT * FROM `user_login` WHERE `email`='$email'";
        $result=mysqli_query($con,$query);
        $row=mysqli_fetch_assoc($result);
        $ver_status = $row['verify_status']; 
        if(mysqli_num_rows($result) > 0 && $ver_status=='V')
        {
            
            $name=$row['name'];
            $web= 'reset password at kingfish logistics';
            $id=$row['id'];
            $sql="UPDATE `user_login` SET `otp`='$otp' WHERE `id`='$id'";
            if(mysqli_query($con,$sql))
            {
                // $api="srYAixWrBQ3FLmzSh4NZhv0F4Y1WEmaTEpvq1v4S";
                // $message = "Hi {$name}, Your Otp is {$otp}. OTP request for {$web}. Don't Share with Anyone. Thanks, Team SB Genus.";
                //   $fields = array(
                //       'mobile_numbers' => $mobile,
                //       'template_id' => "547896854123654",
                //       'message' => $message
                //   );
                //   $sb = curl_init();
                //   curl_setopt($sb, CURLOPT_URL, "https://developers.sbgenus.com/bulksms/host/");
                //   curl_setopt($sb, CURLOPT_POSTFIELDS, $fields);
                //   curl_setopt($sb, CURLOPT_RETURNTRANSFER, true);
                //   curl_setopt($sb, CURLOPT_HTTPHEADER, array(
                //       "Api_key: $api",
                //       "accept: */*",
                //       "cache-control: no-cache",
                //       "content-type: multipart/form-data"
                //   ));
                //   $response = curl_exec($sb);
                //   $error = curl_error($sb);
                //   curl_close($sb);
                //   if($error){
                //       echo $error;
                //   }
                //   else{
                //       header('location:forgot_password.php?otp_sent='.$id);
                //     // echo $response;
                //   }
                
                $headers  = 'MIME-Version: 1.0' . "\r\n";
                $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
                $headers .= 'From: <noreply@kingfishlogistics.com>' . "\r\n";  
                $to = $email;
                $subject = 'OTP Verification For forgot password at kingfish logistics';
                ob_start();
                include("email_temp.php");
                $message = ob_get_contents();
                ob_get_clean();
                $mail = mail($to, $subject, $message, $headers);
                if($mail)
                {
                     header('location:forgot_password.php?otp_sent='.$id);
                }
            }
        }
        else
        {
            header('location:forgot_password.php?otp_not_sent');
        }
    }

    if(isset($_POST['reset_send_otp']))
    {
        $id=$_POST['id'];
        $otp=$_POST['otp'];
        $query="SELECT * FROM `user_login` WHERE `id`='$id'";
        $result=mysqli_query($con,$query);
        $row=mysqli_fetch_assoc($result);
        $prv_otp=$row['otp'];
        if($prv_otp===$otp)
        {
            header('location:forgot_password.php?otp_verify='.$id);
        }
        else
        {
            header('location:forgot_password.php?otp_not_verify='.$id);
        }
    }

    if(isset($_POST['change_password']))
    {
        $id=$_POST['id'];
        $password=md5($_POST['password']);
        
        $query="UPDATE `user_login` SET `user_password`='$password'  WHERE `id`='$id'";
        
        if(mysqli_query($con,$query))
        {
            header('location:index.php?chnge_pass');
        }
    }

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
// $ch = curl_init();

// curl_setopt($ch, CURLOPT_URL, 'https://staging-express.delhivery.com/api/kinko/v1/invoice/charges/.json?md=E&ss=RTO&d_pin=712102&o_pin=431125&cgm=2000&pt=Pre-paid&cod=0');
// curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
// curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


// $headers = array();
// $headers[] = 'Content-Type: application/json';
// $headers[] = 'Authorization: Token api-token-key Pass Token as "Token 6e76b1a14965600bfa11cf330b259ccd81ddc582"';
// curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

// $result = curl_exec($ch);
// if (curl_errno($ch)) {
//     echo 'Error:' . curl_error($ch);
// }
// curl_close($ch);
// echo $result;
